schema_version = "1.0.0"
id = "rmKit"
version = "1.0.11"
name = "rmKit"
tagline = "Tools and Utils for Modeling and GameWorkflows"
maintainer = "Timothee Yeramian <lead.acrysoft@gmail.com>"
type = "add-on"

license = [
  "SPDX:GPL-3.0-or-later",
]

website = "https://rmkit.readthedocs.io/en/latest/"
tags = ["3D View", "Modeling", "Mesh", "Object", "Material"]

blender_version_min = "4.2.0"

wheels = [
  "./wheels/rmlib-0.1.2-py3-none-any.whl"
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git",
  ".*",
  "*.zip",
  "*.bat",
  "*.hot",
  "*.md",
]